### ISSUE TITLE
init should fail gracefully if the folder already exists

### ISSUE THREAD

**Issue by ColinFay** [ColinFay/webrcli#9]
```
colinfay@Colins-MacBook-Pro /tmp % webrcli init spondeboee
👉 Initializing project ----
(This may take some time, please be patient)
⏳ launching npm init, installing webr & spidyr----
🗂️ Copying project skeleton from spidyr----
node:fs:1398
  handleErrorFromBinding(ctx);
  ^

Error: EEXIST: file already exists, mkdir '/private/tmp/spondeboee/webr_packages'
    at Object.mkdirSync (node:fs:1398:3)
    at init (/opt/homebrew/lib/node_modules/webrcli/src/init.js:51:6)
    at Object.handler (/opt/homebrew/lib/node_modules/webrcli/bin/index.js:22:7)
    at /opt/homebrew/lib/node_modules/webrcli/node_modules/yargs/build/index.cjs:1:8993
    at j (/opt/homebrew/lib/node_modules/webrcli/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/opt/homebrew/lib/node_modules/webrcli/node_modules/yargs/build/index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (/opt/homebrew/lib/node_modules/webrcli/node_modules/yargs/build/index.cjs:1:9604)
    at _.runCommand (/opt/homebrew/lib/node_modules/webrcli/node_modules/yargs/build/index.cjs:1:7231)
    at [runYargsParserAndExecuteCommands] (/opt/homebrew/lib/node_modules/webrcli/node_modules/yargs/build/index.cjs:1:58539)
    at te.parse (/opt/homebrew/lib/node_modules/webrcli/node_modules/yargs/build/index.cjs:1:40478) {
  errno: -17,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: '/private/tmp/spondeboee/webr_packages'
}

Node.js v18.17.1
```

**Comment by ColinFay** [comment]
closed via #11
